name: Deploy Weather Dashboard

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create config.js from secret
        run: echo "const API_KEY = '${{ secrets.WEATHER_API_KEY }}';" > config.js

      - name: Deploy (example step)
        run: |
          echo "Deploy your app here."
          # For GitHub Pages, you might use peaceiris/actions-gh-pages or similar
