name: Deploy Weather Dashboard

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create config.js from secret
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          if [ -z "$WEATHER_API_KEY" ]; then
            echo "Error: WEATHER_API_KEY secret is not set."
            exit 1
          fi
          echo "const API_KEY = '$WEATHER_API_KEY';" > config.js
          # If using a publish directory, also copy config.js there
          if [ -d "./dist" ]; then
            cp config.js ./dist/
          fi
          if [ -d "./build" ]; then
            cp config.js ./build/
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./